%% Run analysis and save mouse grab data as excel xls

disp('Select the .mat files to be analyzed. You can select multiple files.');
[filename, pathname, filterindex] = uigetfile( ...
       {'*.mat','MAT-files (*.mat)'}, ...
        'Pick .mat file to analyze', ...
        'MultiSelect', 'on');

data = {'videoFile',...
    'Relative Distance',...
    'Relative Angle of Approach',...
    'Relative Distance - X',...
    'Relative Distance - Y',...
    'Grab',...
    'Pellet Absolute - X',...
    'Pellet Absolute - Y',...
    'Paw Absolute - X',...
    'Paw Absolute - Y'
};
modeFlag = 'background';
for i = 1:length(filename)
    r = [];
    theta = [];
    diffXY = [];
    outcome = {};
    traceVideoFile = {};
    refCentroid = [];
    pawCentroid = [];
    load(fullfile(pathname, filename{i}),'videoFile','roiData', 'grabResult');
    [r,theta,diffXY,grabType,refCentroid,pawCentroid] = analyzeMouseAction(roiData, grabResult, videoFile, modeFlag);

    indx = find(~strcmp(grabType,''));
    for j = 1:length(indx)
        data = [data; {videoFile,...
            r(indx(j)),...
            theta(indx(j)),...
            diffXY(indx(j),1),...
            diffXY(indx(j),2),...
            grabType{indx(j)},...
            refCentroid(1,1),...
            refCentroid(1,2),...
            pawCentroid(indx(j),1),...
            pawCentroid(indx(j),2)}];
    end
end